### PR TITLE
Added Splash Screen

### PR DESCRIPTION
**Pull request by Sparker0i**

### CODE REVIEW

**Comment by akarshan96** [comment]
@Sparker0i Can you share the screenshot and apk. Cheers.

**Comment by Sparker0i** [comment]
Well for now it shows the current app logo (which is a round icon) , along with the spinner, it spins for 3s, and then load the MainActivity

**Comment by Sparker0i** [comment]
I will post the screenshots tomorrow

**Comment by akarshan96** [comment]
@Sparker0i code looks okay to me. Since travis is not added to the repo, the screenshot is just to see whether app is building or not. I will merge after the screenshot. Thanks 👍

**Comment by RaiVaibhav** [comment]
@Sparker0i can you change the commit message and provide a reference of issue in that PR commit message it will be easy to see PR request from issue section

**Comment by Sparker0i** [comment]
Sure. Could you please guide me to how to reference that issue in a PR. I'm
pretty new to contributing to other sources, that's why I asked.

And what would you like to have the commit message as?

**Comment by RaiVaibhav** [comment]
@Sparker0i  go through https://help.github.com/articles/closing-issues-using-keywords/ and just add Closes #issue_no in your commit message,it will get referenced automatically

**Comment by Sparker0i** [comment]
Sure will do today evening

**Comment by Sparker0i** [comment]
@akarshan96 here are the screenshots. the icon is kinda enlarged for now, we can fix that later

**Comment by akarshan96** [comment]
@Sparker0i Looks good 👍. Yeah, we can change image later.

**Comment by Sparker0i** [comment]
Thanks :+1:

**Pull request merged**
